add additional tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -3,14 +3,51 @@ name: Tests
 on:
   pull_request:
     types: [opened, reopened, synchronize]
-  push:
-    branches:
-      - "main"
 
 permissions:
   contents: read
 
 jobs:
+  verify-sql:
+    name: Verify SQLC
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+
+      - name: Setup Go
+        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
+        with:
+          go-version: "1.26.6"
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v7
+
+      - name: Install Taskfile
+        uses: go-task/setup-task@a00fbb05ce67b35648be3c78cbc9fd85354c757e # v2.2.0
+
+      - name: Verify SQLC diffs
+        run: task gen:sql:diff
+
+      - name: Verify Swagger diffs
+        run: |
+          task gen:docs
+          # Fail if there are any changes
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Error: Uncommitted or untracked changes found"
+            exit 1
+          fi
+
+      - name: Verify webapp generated clients
+        run: |
+          pnpm install
+          pnpm run gen:api
+          # Fail if there are any changes
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Error: Uncommitted or untracked changes found"
+            exit 1
+          fi
+
   test:
     name: Run tests
     runs-on: ubuntu-latest
